In [12]:
import pandas as pd
import numpy as np

In [13]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

In [14]:


df

   calories  duration
0       420        50
1       380        40
2       390        45

In [15]:
#| label: tbl:kindetic-params

# Create the first DataFrame
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
}, index=['K0', 'K1', 'K2'])

# Create the second DataFrame with different columns and index
df2 = pd.DataFrame({
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
}, index=['K0', 'K2', 'K3'])

# Concatenate the DataFrames with a hierarchical index
df_concat = pd.concat([df1, df2], 
                      keys=['df1', 'df2'],  # Add keys for hierarchical indexing
                      axis=1,  # Concatenate along rows
                      join='outer', # Use 'outer' join to keep all columns
                      sort=False) # Avoid sorting the index

# Print the concatenated DataFrame
df_concat

    df1       df2
      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C1   D1
K3  NaN  NaN   C2   D2